'use client';

import { useState } from 'react';

interface QA {
  q: string;
  a: string;
}

const FAQS: QA[] = [
  {
    q: 'How is this different from free horoscope apps?',
    a: 'VedicHour gives you 18 hourly windows per day, rated 0–100, in your current city\'s local time — powered by Swiss Ephemeris with Lahiri Ayanamsa and Vimshottari Dasha. Free apps give one daily reading; we give you the specific hours to act and the specific hours to rest, with written commentary for each.',
  },
  {
    q: 'Is this actually based on real Vedic astrology?',
    a: 'Yes. We use Swiss Ephemeris (the same engine professional astrologers use) and the Lahiri Ayanamsa sidereal system. Every score is derived from real planetary positions at your birth and the forecast hour — hora rulership, choghadiya, Rahu Kaal, transit lagna, and dasha period are all computed, not guessed. The written commentary is then generated by AI from that astrological data.',
  },
  {
    q: 'How fast is delivery?',
    a: 'Reports typically generate in 3–8 minutes on our servers. You can safely close the tab — it keeps running and you\'ll find the report in your dashboard when you return.',
  },
  {
    q: 'What do I need to provide?',
    a: 'Your birth date, exact birth time (important — rounded times reduce accuracy), and birth city. Your current city is used for the local-time hourly schedule. We never share or sell any of this.',
  },
  {
    q: 'What happens if I\'m not satisfied?',
    a: 'We offer a 48-hour no-questions-asked refund. Email support@vedichour.com and we\'ll process it directly with our payment partner. See /refund for the full policy.',
  },
  {
    q: 'Is my data safe?',
    a: 'Yes. All data is TLS-encrypted in transit and at rest. We never sell your personal data. Payments are handled by PCI-DSS compliant partners (Ziina / Razorpay) — we never see your card details. You can request deletion anytime at privacy@vedichour.com.',
  },
  {
    q: 'Which payment methods are supported?',
    a: 'We accept international cards (Visa, Mastercard, Amex) via Ziina. For customers in India, Razorpay handles UPI, cards, and net banking. Prices auto-adjust to INR, AED, or USD based on your location.',
  },
  {
    q: 'Can I gift a report to someone else?',
    a: 'Yes — just enter their birth details during onboarding. The report is bound to your account, so you can download and share the PDF/Markdown with them.',
  },
];

function ChevronIcon({ open }: { open: boolean }) {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      className={`transition-transform duration-200 ${open ? 'rotate-180' : ''}`}
      aria-hidden
    >
      <path
        d="M6 9l6 6 6-6"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

export default function FAQ() {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  // FAQPage JSON-LD for SEO
  const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQS.map(({ q, a }) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: { '@type': 'Answer', text: a },
    })),
  };

  return (
    <section id="faq" className="py-24 md:py-28 bg-space relative">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <div className="section-divider absolute top-0 left-0 right-0" />

      <div className="max-w-3xl mx-auto px-6">
        <div className="section-header text-center">
          <p className="section-eyebrow">Questions</p>
          <h2 className="section-title text-display-md">Frequently Asked</h2>
          <p className="section-subtitle text-body-lg mx-auto">
            Everything you might want to know before you generate a report.
          </p>
        </div>

        <div className="space-y-3 mt-10">
          {FAQS.map((qa, i) => {
            const open = openIdx === i;
            return (
              <div
                key={qa.q}
                className={`card overflow-hidden transition-colors ${open ? 'border-amber/30' : ''}`}
              >
                <button
                  type="button"
                  onClick={() => setOpenIdx(open ? null : i)}
                  aria-expanded={open}
                  aria-controls={`faq-panel-${i}`}
                  className="w-full px-5 sm:px-6 py-4 flex items-center justify-between gap-4 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber/40 rounded-card"
                >
                  <span className="font-body font-medium text-star text-body-md">
                    {qa.q}
                  </span>
                  <span className="text-amber/70 shrink-0">
                    <ChevronIcon open={open} />
                  </span>
                </button>
                <div
                  id={`faq-panel-${i}`}
                  role="region"
                  className={`grid transition-all duration-250 ease-out ${
                    open ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'
                  }`}
                >
                  <div className="overflow-hidden">
                    <p className="px-5 sm:px-6 pb-5 text-dust text-body-sm leading-relaxed">
                      {qa.a}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        <p className="text-center mt-10 text-dust/60 text-body-sm">
          Something not answered? Email{' '}
          <a
            href="mailto:support@vedichour.com"
            className="text-amber hover:underline"
          >
            support@vedichour.com
          </a>
          .
        </p>
      </div>
    </section>
  );
}
