import Link from 'next/link'
import type { Metadata } from 'next'

export const dynamic = 'force-static'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'The terms that govern use of VedicHour — eligibility, pricing, digital delivery, refunds, and our responsibilities.',
  alternates: { canonical: '/terms' },
  openGraph: {
    title: 'Terms of Service · VedicHour',
    description: 'Terms governing use of VedicHour reports and services.',
    url: '/terms',
    type: 'article',
  },
  twitter: {
    card: 'summary',
    title: 'Terms of Service · VedicHour',
    description: 'Terms governing use of VedicHour reports and services.',
  },
}

const sections = [
  { title: '1. Acceptance of Terms', content: 'By accessing or using VedicHour ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These Terms constitute a legally binding agreement between you and VedicHour. We reserve the right to modify these Terms at any time. Continued use following changes constitutes acceptance.' },
  { title: '2. Description of Service', content: 'VedicHour provides AI-assisted Vedic astrology reports as digital products. Reports include natal chart analysis, hourly forecasts, choghadiya timing, planetary position analysis, and astrological commentary. Astronomical calculations are performed using the Swiss Ephemeris; narrative interpretations are generated by Claude Sonnet 4 (Anthropic). All reports are delivered digitally.' },
  { title: '3. Eligibility', content: 'You must be at least 18 years of age to use the Service. By using the Service, you represent that you meet this requirement and have the legal capacity to enter a binding agreement.' },
  { title: '4. Digital Products and Delivery', content: 'Upon successful payment, your report will be available typically within 3–8 minutes, up to 15 minutes in rare cases of high demand. Reports are delivered via downloadable PDF and online viewing. Delivery is deemed complete upon making the report available in your account or sending a download link to your registered email.' },
  { title: '5. Payment and Pricing', content: 'Prices are displayed in your local currency where supported (INR, AED, USD). The final charge currency is shown at checkout. Payments are processed by our authorized payment partner Ziina. By providing payment information, you authorize Ziina to charge the fees shown at checkout. We reserve the right to change pricing at any time; changes will not affect completed purchases.' },
  { title: '6. Refund Policy', content: 'We offer a 24-hour satisfaction guarantee on all paid reports. Request a refund within 24 hours of purchase by emailing support@vedichour.com. Refunds are processed within 5-10 business days. See our full Refund Policy at vedichour.com/refund.' },
  { title: '7. Astrological Disclaimer', content: 'IMPORTANT: VedicHour reports are informational guidance for self-reflection and planning. They do not substitute professional medical, legal, or financial advice. Astronomical calculations are deterministic and based on Swiss Ephemeris; narrative interpretations are AI-generated. We do not guarantee any particular outcome from using our reports. Do not make important life decisions based solely on our reports. We expressly disclaim liability for decisions made in reliance on our content.' },
  { title: '8. Intellectual Property', content: 'All VedicHour content is our intellectual property. Upon purchase, you receive a personal, non-exclusive, non-transferable license for personal, non-commercial use. You may not reproduce, distribute, sell, or create derivative works without written permission.' },
  { title: '9. User Data and Privacy', content: 'We collect birth data and contact information to generate and deliver your report. Data is handled per our Privacy Policy at vedichour.com/privacy, incorporated herein by reference. We do not sell your personal data.' },
  { title: '10. Prohibited Use', content: 'You agree not to: use the Service unlawfully; reverse-engineer our software; use automated systems beyond personal use; resell or sublicense our reports; submit false information when purchasing; or use the Service to harm others.' },
  { title: '11. Limitation of Liability', content: 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, VEDICHOUR SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE SPECIFIC REPORT IN QUESTION.' },
  { title: '12. Warranty Disclaimer', content: 'THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. Astrological interpretations are subjective and we make no warranty regarding their accuracy.' },
  { title: '13. Governing Law', content: 'These Terms are governed by the laws of the United Arab Emirates. Disputes shall be subject to the exclusive jurisdiction of the courts of Dubai, UAE.' },
  { title: '14. Contact', content: 'Questions about these Terms: support@vedichour.com | vedichour.com' },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-space via-dark to-space text-star font-display">
      <header className="px-5 sm:px-8 lg:px-12 py-5 flex justify-between items-center border-b border-amber/15">
        <Link
          href="/"
          className="no-underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber/60 rounded-sm"
        >
          <span className="text-xl sm:text-2xl font-bold text-amber tracking-wider font-mono">VedicHour</span>
        </Link>
        <Link
          href="/pricing"
          className="text-dust/60 hover:text-amber transition-colors text-sm font-mono no-underline focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-amber/60 rounded-sm"
        >
          Pricing →
        </Link>
      </header>

      <main id="main-content" className="max-w-[780px] mx-auto px-5 sm:px-8 pt-14 sm:pt-20 pb-20 sm:pb-28">
        <p className="text-xs tracking-[0.2em] text-amber uppercase mb-3 font-mono">Legal</p>
        <h1 className="text-4xl sm:text-5xl font-light mb-4 leading-tight">Terms of Service</h1>
        <p className="text-sm text-dust/50 font-sans mb-12">Last updated: 18 April 2026</p>

        {/* Summary callout */}
        <div className="bg-amber/[0.05] border border-amber/20 rounded-xl px-7 py-6 mb-12 text-sm text-dust/70 font-sans leading-relaxed">
          <strong className="text-amber">Summary:</strong> VedicHour provides AI-assisted Vedic astrology reports for reflection and planning. We offer a 24-hour refund guarantee. Reports are not a substitute for professional advice. Your data is used only to generate your report.
        </div>

        {/* Sections */}
        {sections.map((s, i) => (
          <div key={i} className="py-8 border-b border-white/[0.06]">
            <h2 className="text-base font-semibold mb-4 text-amber font-display">{s.title}</h2>
            <p className="text-sm text-dust/70 leading-[1.8] font-sans">{s.content}</p>
          </div>
        ))}
      </main>

      <footer className="border-t border-white/6 px-5 sm:px-8 lg:px-12 py-7 flex flex-col sm:flex-row justify-between items-center gap-4 font-mono text-xs text-dust/50">
        <span>© {new Date().getFullYear()} VedicHour. All rights reserved.</span>
        <div className="flex gap-5 sm:gap-6">
          <Link href="/privacy" className="text-dust/50 hover:text-amber transition-colors no-underline focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-amber/60 rounded-sm">Privacy</Link>
          <Link href="/refund" className="text-dust/50 hover:text-amber transition-colors no-underline focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-amber/60 rounded-sm">Refunds</Link>
        </div>
      </footer>
    </div>
  )
}
